CREATE TABLE EMPLOYEES (
    ID INT PRIMARY KEY NOT NULL,
    NAME CHAR(20) NOT NULL,
    AGE INT NOT NULL
);

INSERT INTO EMPLOYEES (ID, NAME, AGE) 
VALUES (1,'Rahul',22),(2,'Shubham',23),(3,'David',21),(4,'Yash',21);
